/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.elements.PseudoText;
import org.apache.commons.lang3.StringUtils;

public class App {
    public static void main(String[] args) {
        String title = "DevOps Abgabe 1";
        System.out.println("Projektname: " + StringUtils.upperCase(title));

        Render render = new Render();
        IContextBuilder builder = render.newBuilder();
        builder.width(120).height(20);
        builder.element(new PseudoText("paramrah"));
        ICanvas canvas = render.render(builder.build());

        System.out.println(canvas.getText());
    }
}