/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.elements.PseudoText;
import com.google.common.base.Joiner;
import com.google.common.collect.ImmutableList;
import org.apache.commons.lang3.StringUtils;
import org.fusesource.jansi.Ansi;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import java.io.File;
import java.io.IOException;

public class App {
    public static void main(String[] args) {


        String projectName = "devops ln1";
        String title = StringUtils.upperCase(projectName); // Projektname in Großbuchstaben umwandeln mit Apache Commons Lang

        System.out.println("======================================");
        System.out.println("Projekt: " + title);
        System.out.println("======================================");

        // Build-Schritte in einer Liste speichern und mit Guava's Joiner zu einem String verbinden
        ImmutableList<String> steps = ImmutableList.of(
                "Gradle-Projekt erstellt",
                "Dependencies eingebunden",
                "GitHub verwendet",
                "Build erfolgreich"
        );

        String summary = Joiner.on(" -> ").join(steps);
        System.out.println(summary);
        System.out.println();


        // ASCII-Art mit AsciiRender erstellen
        Render render = new Render();
        IContextBuilder builder = render.newBuilder();
        builder.width(150).height(20);
        builder.element(new PseudoText("paramrah"));
        ICanvas canvas = render.render(builder.build());

        System.out.println(canvas.getText());

        System.out.println();
        System.out.println(Ansi.ansi().fgBlue().a("Projektinformationen").reset()); // Überschrift in Blau mit Jansi
        System.out.println("--------------------------------------");

        // Tabellenkopf
        System.out.printf("%-20s | %-20s%n", "LN1", "Devops");
        System.out.println("--------------------------------------");

        // Tabelleninhalt
        System.out.printf("%-20s | %-20s%n", "Name", "Rahul Parameswaran");
        System.out.printf("%-20s | %-20s%n", "Klasse", "WIN24a");
        System.out.printf("%-20s | %-20s%n", "E-Mail", "paramrah@students.zhaw.ch");
        System.out.printf("%-20s | %-20s%n", "Github Username", "cfo37");

        System.out.println("--------------------------------------");

        // PDF erstellen mit Apache PDFBox
        try {
            PDDocument document = new PDDocument();
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            PDPageContentStream contentStream = new PDPageContentStream(document, page);

            contentStream.beginText();
            contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 20);
            contentStream.newLineAtOffset(50, 750);
            contentStream.showText("DevOps Build Report");

            contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
            contentStream.newLineAtOffset(0, -40);
            contentStream.showText("Projekt: " + title);

            contentStream.newLineAtOffset(0, -25);
            contentStream.showText("Name: Rahul Parameswaran");

            contentStream.newLineAtOffset(0, -25);
            contentStream.showText("Klasse: WIN24a");

            contentStream.newLineAtOffset(0, -25);
            contentStream.showText("E-Mail: paramrah@students.zhaw.ch");

            contentStream.newLineAtOffset(0, -25);
            contentStream.showText("GitHub Username: cfo37");

            contentStream.newLineAtOffset(0, -25);
            contentStream.showText("Build-Schritte: " + summary);

            contentStream.endText();
            contentStream.close();

            document.save(new File("build-report.pdf"));
            document.close();

            System.out.println();
            System.out.println(Ansi.ansi().fgGreen().a("PDF erfolgreich erstellt: build-report.pdf").reset()); // Erfolgsmeldung in Grün mit Jansi

        } catch (IOException e) {
            System.out.println(Ansi.ansi().fgRed().a("Fehler beim Erstellen des PDFs.").reset());  // Fehlermeldung in Rot mit Jansi
            e.printStackTrace();
        }
    }
}